services:
    app:
        build: .
        container_name: python_dev_env
        env_file:
            - .env
        command: sleep infinity
        volumes:
            - .:/app
        
# build: . - specify that we want to build from the local Dockerfile
# to run - we need to just run 1 command: docker compose up

