services:
    app:
        build: .
        container_name: python_dev_env
        env_file:
            - .env
        command: sleep infinity
        volumes:
            - .:/app
        
# build: . - specifies that you want to build from the local Dockerfile
# to run, you need to execute a single command: docker compose up
